include:
  - component: $CI_SERVER_FQDN/cdso/cdso/review@main
    inputs:
      name: "distroless"
      pipeline_type: "base-container"
      cdso_branch: main

get-packages:
  stage: pre-build
  image: registry.cdso.army.mil/cdso/containers/approved-base/ubuntu:24.04
  script:
    - sh tools/packages.sh
  artifacts:
    paths:
    - packages.tgz
    - symlinks.tgz
    expire_in: 1 hour
