trufflehog:
  false_positives: [] # was used for dod certs
  excluded_files: []
deployment_level: "PRODUCTION"
organization: "cdso"
security_group: "dami_im"

distroless:
  project_type: "base"
  dockerfile_folder: "."
  container_lifespan: "MULTIPLE"
  connection_context: "NONE"
  container_spec:
    root_user: >-
      This base container ships with the root user as the default to support
      derivative containers, which should create a new non-root user.
    non_minimized: ""
  mitigations: []
  semgrep:
    exclusions: [] # rule exclusions
    rule_sets: [] # will use 'community' by default
    ignore: [] # files and paths to ignore, supports glob pattern: https://git-scm.com/docs/gitignore#_pattern_format
  clamav:
    false_positives: []
  zap:
    skip_reason: "This image is a base to be used to test other images, and therefore doesn't have a service to be scanned."
    debug: false
    cert_path: ""
    port: 65534
    service_ports: []