include:
  - component: $CI_SERVER_FQDN/cdso/cdso/review@main
    inputs:
      name: "distroless"
      pipeline_type: "base-container"
      cdso_branch: main

variables:
  DEFAULT_DEBIAN_RELEASE_TAG: "debian-13.0"

resolve-debian-version:
  stage: .pre
  image: registry.cdso.army.mil/cdso/containers/approved-base/debian:v13.0
  script:
    - sh tools/version.sh debian.env
  artifacts:
    reports:
      dotenv: debian.env
    expire_in: 1 hour

get-packages:
  stage: pre-build
  image: ${DEBIAN_PARENT_IMAGE}
  needs:
    - job: resolve-debian-version
      artifacts: true
  script:
    - sh tools/packages.sh
  artifacts:
    paths:
      - packages.tgz
      - symlinks.tgz
    reports:
      dotenv: debian.env
    expire_in: 1 hour
